### PR TITLE
solves issue #222

### PR DESCRIPTION
**Pull request by Debarpan08**
Added Patience Sort.cpp

### CODE REVIEW

**Comment by Debarpan08** [comment]
Added PatienceSort.cpp to the sorting-algorithms repo

**Review by tulika-99 — APPROVED** [review]
loved this. Didn't know of this before

**Comment by Debarpan08** [comment]
Thank you so very much, Ma'am.

**Comment by Debarpan08** [comment]
Ma'am,you have approved the PR on the sorting algorithm,right?Actually it's
not showing that it has been merged.Thank you!

**Comment by Debarpan08** [comment]
@tulika-99  Ma'am, I am a hacktober 2022 participant can you please add in necessary labels so that this pr is tracked by hacktober site

**Pull request merged**
