### PR TITLE
Linear Search

### PR DESCRIPTION
**Pull request by Karan-Dhingra**
This program is in C++ Language

### CODE REVIEW

**Comment by tulika-99** [comment]
There is no such thing as Linear sort. This is a program for Linear Search. Sorting an Array means arranging an array in a specific order.

**Comment by tulika-99** [comment]
There is no such thing as Linear sort. This is a program for Linear Search. Sorting an Array means arranging an array in a specific order.

**Comment by Karan-Dhingra** [comment]
Yes yes after i done that i realize my mistake 😅 I tried to change it but I was unable to do so

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Karan-Dhingra** [comment]
I will change it again 😅 and this time I will add it at correct location

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by tulika-99** [comment]
lol no problem

**Comment by Karan-Dhingra** [comment]
I have made one more pull request please see it.

**Pull request closed without merging**
