### PR TITLE
Added BogoSort-Java

### PR DESCRIPTION
**Pull request by johnli01**
Implemented the Bogo Sort algorithm in Java as well as a Bogo Sort algorithm text file

### CODE REVIEW

**Comment by tulika-99** [comment]
@johnli01 Hi ! sorry but can you pls re-clone the repo and then add this in the new folder .There was some restructuring done. Thnx

**Comment by johnli01** [comment]
What new folder are you referring to? I do not see it, maybe pull from master?

**Comment by tulika-99** [comment]
just create one with the name of Bogo Sort

**Comment by johnli01** [comment]
Oh i thought I made a new folder for it already. Did you want me to just delete the clone and reclone it then recreate the folder with all the code?

**Comment by tulika-99** [comment]
yes exactly

**Comment by tulika-99** [comment]
or wait its easier if I do that

**Pull request merged**
