### PR TITLE
added quick sort in C

### PR DESCRIPTION
**Pull request by EliasJuniorNino**

### CODE REVIEW

**Comment by EliasJuniorNino** [comment]
done

**Comment by tulika-99** [comment]
Hi since we have restructured the entire repo after you pull request was made , your branch is incompatible for merging.
In order to resolve this you need to repeat the procedure i.e. clone the repo (the latest version) and then add your folder to the respective algo's folder.

**Comment by EliasJuniorNino** [comment]
ok, i'll be doing this

**Comment by EliasJuniorNino** [comment]
done

**Pull request closed without merging**
